services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: gestor-motores-mosquitto
    restart: unless-stopped

    ports:
      - "1883:1883"

    volumes:
      - ./infrastructure/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./infrastructure/mosquitto/config/passwords:/mosquitto/config/passwords:ro
      - ./infrastructure/mosquitto/config/acl:/mosquitto/config/acl:ro
      - mosquitto_data:/mosquitto/data

    networks:
      - gestor_motores_network

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: gestor-motores-timescaledb
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./infrastructure/database/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - gestor_motores_network

volumes:
  timescaledb_data:
    name: gestor-motores-timescaledb-data

  mosquitto_data:
    name: gestor-motores-mosquitto-data

networks:
  gestor_motores_network:
    name: gestor-motores-network
    driver: bridge