BEGIN;

DROP TABLE IF EXISTS alarms;
DROP TABLE IF EXISTS telemetry;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS motors;
DROP TABLE IF EXISTS plants;
DROP TABLE IF EXISTS clients;

DROP FUNCTION IF EXISTS set_updated_at();

COMMIT;
